server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: service-two
  zipkin:
    base-url: http://localhost:8086
  boot:
    admin:
      client:
        url: http://localhost:8200
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss SSS,GMT+8} [%X{X-B3-TraceId:-},%X{X-B3-ParentSpanId:-},%X{X-B3-SpanId:-}] [%thread] %-5level %logger{50} - %msg%n'
#  level:
#    com:
#      example:
#        mapper: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
feign:
  hystrix:
    enabled: true
info:
  app:
    name: ${spring.application.name}
    version: @version@
mybatis:
  mapper-locations: classpath:com/quyc/servicetwo/*/*.xml