# ==Tomcat配置==
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8080/eureka/
spring:
  application:
    name: api-one
  zipkin:
    base-url: http://localhost:8086
logging:
  pattern:
    console:
