# ==Tomcat配置==
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8080/eureka/
spring:
  application:
    name: api-one
  zipkin:
    base-url: http://localhost:8086
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss SSS,GMT+8} [%X{X-B3-TraceId:-},%X{X-B3-ParentSpanId:-},%X{X-B3-SpanId:-}] [%thread] %-5level %logger{50} - %msg%n'
