info:
  app:
    name: ${spring.application.name}
    version: @version@
server:
  port: 8180
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: gateway
#  zipkin:
#    base-url: http://localhost:8086
#  boot:
#    admin:
#      client:
#        url: http://localhost:8200
  main:
    allow-bean-definition-overriding: true
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss SSS,GMT+8} [%X{X-B3-TraceId:-},%X{X-B3-ParentSpanId:-},%X{X-B3-SpanId:-}] [%thread] %-5level %logger{50} - %msg%n'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
