info:
  app:
    name: ${spring.application.name}
    version: @version@
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: zuul
  zipkin:
    base-url: http://localhost:8086
  boot:
    admin:
      client:
        url: http://localhost:8200
# zuul config -> ZuulProperties
zuul:
  routes:
    api-one:
      path: /api-one/**
      serviceId: api-one
    api-two:
      path: /api-two/**
      serviceId: api-two
  retryable: false
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss SSS,GMT+8} [%X{X-B3-TraceId:-},%X{X-B3-ParentSpanId:-},%X{X-B3-SpanId:-}] [%thread] %-5level %logger{50} - %msg%n'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true # 默认为true
ribbon:
  retryable: false
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ConnectTimeout: 1000
  ReadTimeout: 15000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 12000 # 此处超时后不会立刻返回，而是等ribbon.ReadTimeout超时后返回，不过即便此时返回数据也只会返回超时信息