server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: zuul
  zipkin:
    base-url: http://localhost:8086
zuul:
  routes:
    api-one:
      path: /api-one/**
      serviceId: api-one
    api-two:
      path: /api-two/**
      serviceId: api-two
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss SSS,GMT+8} [%X{X-B3-TraceId:-},%X{X-B3-ParentSpanId:-},%X{X-B3-SpanId:-}] [%thread] %-5level %logger{50} - %msg%n'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
feign:
  hystrix:
    enabled: true
info:
  app:
    name: ${spring.application.name}
    version: @version@