server:
  port: 8080
eureka:
  instance:
    hostname: localhost
    health-check-url-path: /health #健康检查地址
    status-page-url-path: /info #状态页的url地址
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8080/eureka/
  server:
    enableSelfPreservation: false           # 关闭自我保护模式（缺省为打开）

