info:
  app:
    name: ${spring.application.name}
    version: @version@
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8080/eureka/
spring:
  application:
    name: service-one
  zipkin:
    base-url: http://localhost:8086

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss SSS,GMT+8} [%X{X-B3-TraceId:-},%X{X-B3-ParentSpanId:-},%X{X-B3-SpanId:-}] [%thread] %-5level %logger{50} - %msg%n'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true # 默认为true
# ribbon config -> CommonClientConfigKey,DefaultClientConfigImpl
ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ConnectTimeout: 2000
  ReadTimeout: 10000
  ServerListRefreshInterval: 1
# hystrix config -> https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 此处超时时间取ribbon.ReadTimeout和timeoutInMilliseconds之间的最小值，超时立刻返回

