info:
  app:
    name: ${spring.application.name}
    version: @version@
server:
  port: 8183
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/quyc07/SpringCloudConfig.git
          search-paths: springcloudbasic
#          username:
#          password:
      label: master
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss SSS,GMT+8} [%X{X-B3-TraceId:-},%X{X-B3-ParentSpanId:-},%X{X-B3-SpanId:-}] [%thread] %-5level %logger{50} - %msg%n'
